server:
  port: 8080

spring:
  application:
    name: metadata-ingest


aws:
  region: us-east-1
  access-key: ${APP_AWS_ACCESS_KEY}
  secret-key: ${APP_AWS_SECRET_KEY}

  s3:
    bucket: ${APP_AWS_S3_BUCKET}

resilience4j:
  circuitbreaker:
    instances:
      fileService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10



management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true